export const settingsSections = [
  {
    id: 'site',
    title: '博客信息',
    description: '填写读者在博客前台会看到的名称、简介和公开访问地址。',
    fields: [
      {
        key: 'site.title',
        label: '站点标题',
        type: 'text',
        placeholder: '例如：Night Journal、深夜漫笔',
        help: '显示在博客首页、浏览器标题和后台页头。',
      },
      {
        key: 'site.subtitle',
        label: '副标题',
        type: 'textarea',
        placeholder: '例如：记录深夜、感知与自我校准的写作站点',
        help: '用于首页说明。写一句 10 到 40 字的介绍即可。',
        wide: true,
      },
      {
        key: 'site.domain',
        label: '绑定域名',
        type: 'text',
        placeholder: 'journal.example.com',
        help: '只填域名本身，不要带 http:// 或 https:// 。',
      },
    ],
  },
  {
    id: 'panel',
    title: '面板设置',
    description: '控制后台左上角的标题与状态文案，只影响管理面板本身。',
    fields: [
      {
        key: 'panel.title',
        label: '面板标题',
        type: 'text',
        placeholder: '留空则沿用博客标题',
        help: '显示在后台左上角。留空时会自动沿用“博客信息”中的站点标题。',
      },
      {
        key: 'panel.status_text',
        label: '面板状态文案',
        type: 'text',
        placeholder: '{user} 正在守夜',
        defaultValue: '{user} 正在守夜',
        help: [
          '显示在标题下方，可直接写成一句短状态。',
          '如果想带上当前登录名，可在文案里使用 {user}，例如：{user} 正在值守。',
        ],
      },
    ],
  },
  {
    id: 'llm',
    title: '大脑接入（LLM）',
    description: '决定正文由哪个模型生成。填完后可在当前区块直接测试。',
    fields: [
      {
        key: 'llm.base_url',
        label: '接口地址（Base URL）',
        type: 'url',
        placeholder: '例如：https://api.openai.com/v1 或你的中转地址',
        help: '填写模型服务的根地址。通常以 /v1 结尾，并兼容 OpenAI Chat Completions。',
      },
      {
        key: 'llm.api_key',
        label: '访问密钥（API Key）',
        type: 'secret',
        placeholder: 'sk-...',
        help: [
          '填写模型服务分配给你的密钥。',
          '保留 ****** 表示不修改当前密钥。',
        ],
      },
      {
        key: 'llm.model_id',
        label: '模型名称（Model ID）',
        type: 'text',
        placeholder: '例如：gpt-4.1-mini、qwen-max、deepseek-chat',
        help: '填写服务商文档里要求的模型名称，用于生成正文。',
      },
    ],
  },
  {
    id: 'embedding',
    title: '记忆检索（Embedding）',
    description: '决定系统如何做记忆检索、相似度判断和去重。填完后可直接测试。',
    fields: [
      {
        key: 'embedding.base_url',
        label: '接口地址（Base URL）',
        type: 'url',
        placeholder: '例如：https://api.openai.com/v1 或你的向量服务地址',
        help: '填写向量模型服务的根地址。若留空，部分流程会回退到大脑接入配置。',
      },
      {
        key: 'embedding.api_key',
        label: '访问密钥（API Key）',
        type: 'secret',
        placeholder: 'sk-...',
        help: [
          '填写向量模型服务的密钥。',
          '保留 ****** 表示不修改当前密钥。',
        ],
      },
      {
        key: 'embedding.model_id',
        label: '模型名称（Model ID）',
        type: 'text',
        placeholder: '例如：text-embedding-3-large、text-embedding-v4',
        help: '用于把记忆和文章内容转成向量，支撑检索与去重。',
      },
    ],
  },
  {
    id: 'schedule',
    title: '发文节奏与预算',
    description: '用“几天几篇”和一个固定时间来安排发文。若一轮里要发多篇，第一篇固定，剩余篇数会在当天随机分布。',
    fields: [
      {
        key: 'schedule.days_per_cycle',
        label: '几天一轮',
        type: 'number',
        placeholder: '1',
        defaultValue: '1',
        help: '例如填 3，表示每 3 天作为一轮来安排发文。改动后会从今天重新开始计算新轮次。',
        min: 1,
        step: 1,
      },
      {
        key: 'schedule.posts_per_cycle',
        label: '一轮发几篇',
        type: 'number',
        placeholder: '1',
        defaultValue: '1',
        help: '例如填 2，配合上面的 3 天一轮，就表示 3 天内发 2 篇。填 0 表示只手动发文。',
        min: 0,
        step: 1,
      },
      {
        key: 'schedule.publish_time',
        label: '默认发文时间',
        type: 'time',
        placeholder: '21:02',
        defaultValue: '21:02',
        help: [
          '使用 24 小时制，例如 21:02。',
          '如果一轮内会发多篇，第一篇固定在这个时间点，剩余篇数会在当天其他时间随机发出。',
        ],
      },
      {
        key: 'schedule.sample_interval_minutes',
        label: '采样间隔（分钟）',
        type: 'number',
        placeholder: '5',
        help: '系统隔多久查看一次环境变化。数值越小，更新越频繁。',
        min: 1,
        step: 1,
      },
      {
        key: 'budget.daily_limit_usd',
        label: '每日预算上限（USD）',
        type: 'number',
        placeholder: '99999',
        defaultValue: '99999',
        help: '默认 99999，视为基本不限制。当天模型费用超过这个数字后，系统才会休眠。',
        min: 0,
        step: 0.01,
      },
    ],
  },
  {
    id: 'quality',
    title: '质量策略',
    description: '控制正文长度、重试次数与质量过滤规则。',
    fields: [
      {
        key: 'qa.max_retries',
        label: '最大重试次数',
        type: 'number',
        placeholder: '3',
        help: 'QA 未通过时允许的最大重写次数。',
        min: 0,
        step: 1,
      },
      {
        key: 'qa.min_length',
        label: '最小长度',
        type: 'number',
        placeholder: '200',
        help: '正文最小字符数。',
        min: 0,
        step: 1,
      },
      {
        key: 'qa.max_length',
        label: '最大长度',
        type: 'number',
        placeholder: '5000',
        help: '正文最大字符数。',
        min: 1,
        step: 1,
      },
      {
        key: 'qa.duplicate_threshold',
        label: '重复阈值',
        type: 'number',
        placeholder: '0.85',
        help: '越高越宽松，通常保持在 0 到 1 之间。',
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: 'qa.forbidden_words',
        label: '禁用词列表',
        type: 'textarea',
        placeholder: '["示例词"]',
        help: '使用 JSON 数组，命中后会进入高风险处理。',
        wide: true,
      },
      {
        key: 'qa.template_phrases',
        label: '模板短语列表',
        type: 'textarea',
        placeholder: '["首先","其次"]',
        help: '使用 JSON 数组，用于识别模板化措辞。',
        wide: true,
      },
    ],
  },
  {
    id: 'advanced',
    title: '高级配置',
    description: '较少改动的运行控制项，默认折叠。',
    collapsible: true,
    fields: [
      {
        key: 'budget.monthly_limit_usd',
        label: '每月预算上限（USD）',
        type: 'number',
        placeholder: '99999',
        defaultValue: '99999',
        help: '默认 99999，适合不做月度限制的场景。只有你确实需要封顶时再调小。',
        min: 0,
        step: 0.01,
      },
      {
        key: 'schedule.review_cron',
        label: '复查时间',
        type: 'schedule',
        placeholder: '0 3 * * 0',
        help: '控制系统定期复查与整理内容的时间。一般无需修改。',
      },
      {
        key: 'schedule.decay_cron',
        label: '维护时间',
        type: 'schedule',
        placeholder: '0 4 * * *',
        help: '控制记忆衰减等后台维护任务的时间。一般保持默认即可。',
      },
      {
        key: 'webhook.auth_mode',
        label: 'Webhook 鉴权模式',
        type: 'text',
        placeholder: 'bearer',
        help: '当前支持 bearer 或 hmac。',
      },
      {
        key: 'webhook.auth_token',
        label: 'Webhook 密钥',
        type: 'secret',
        placeholder: 'token-or-secret',
        help: '保留 ****** 表示不修改当前密钥。',
      },
      {
        key: 'webhook.cooldown_seconds',
        label: 'Webhook 冷却时间（秒）',
        type: 'number',
        placeholder: '1800',
        help: '防止外部事件短时间内重复触发。',
        min: 0,
        step: 1,
      },
      {
        key: 'notify.enabled',
        label: '启用告警通知',
        type: 'boolean',
        help: '开启后，任务失败、熔断和待人工签发会主动推送到通知 Webhook。',
      },
      {
        key: 'notify.webhook_url',
        label: '通知 Webhook URL',
        type: 'url',
        placeholder: 'https://hooks.example.com/quanzhen',
        help: '接收系统告警的 Webhook 地址。',
        wide: true,
      },
      {
        key: 'notify.bearer_token',
        label: '通知 Bearer Token',
        type: 'secret',
        placeholder: 'token',
        help: '可选。保留 ****** 表示不修改当前令牌。',
      },
      {
        key: 'anti_perfection.enabled',
        label: '启用反完美化',
        type: 'boolean',
        help: '开启后系统会在特定条件下降低“过度工整”的倾向。',
      },
      {
        key: 'anti_perfection.consecutive_max',
        label: '连续触发上限',
        type: 'number',
        placeholder: '3',
        help: '连续进入反完美化模式的最大次数。',
        min: 0,
        step: 1,
      },
      {
        key: 'anti_perfection.cooldown_hours',
        label: '反完美化冷却（小时）',
        type: 'number',
        placeholder: '24',
        help: '两次连续触发之间的冷却时间。',
        min: 0,
        step: 1,
      },
      {
        key: 'sensory.blind_zone_minutes',
        label: '感知盲区（分钟）',
        type: 'number',
        placeholder: '30',
        help: '低于该窗口的感知会被视为盲区。',
        min: 0,
        step: 1,
      },
      {
        key: 'sensory.cpu_high_threshold',
        label: 'CPU 高负载阈值',
        type: 'number',
        placeholder: '80',
        help: '单位为百分比。',
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'sensory.mem_high_threshold',
        label: '内存高负载阈值',
        type: 'number',
        placeholder: '85',
        help: '单位为百分比。',
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'sensory.io_high_threshold',
        label: 'IO 高负载阈值',
        type: 'number',
        placeholder: '70',
        help: '单位为百分比。',
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'sensory.source_mode',
        label: '感知来源模式',
        type: 'text',
        placeholder: 'container',
        help: '通常为 container，也可按部署需求切换。',
      },
      {
        key: 'hugo.theme',
        label: 'Hugo 主题',
        type: 'text',
        placeholder: 'PaperMod',
        help: '静态博客主题名称。',
      },
    ],
  },
]

export const settingFields = settingsSections.flatMap((section) => section.fields)

export const settingFieldMap = Object.fromEntries(settingFields.map((field) => [field.key, field]))
